_core:
  default_config_hash: W2w5PXSl9APjHQ6ePlJ0_e1qs-RcC-wTxqvI8iYbYCk
premier: 0
api_key: AIzaSyB4YY5Z6OBM-nb3GYFjPL4l2URVc3pWK6o
secret: 1a6GJdMtWTgClmXdwMQiY0hxhoE=
premium_client_id: ''
premium_crypto_key: ''
icon_url: ''
