_core:
  default_config_hash: W2w5PXSl9APjHQ6ePlJ0_e1qs-RcC-wTxqvI8iYbYCk
premier: 0
api_key: AIzaSyChVfSORAbRZcLzXyQnGd0s8oieAml-oLM
secret: ''   
premium_client_id: ''
premium_crypto_key: ''
icon_url: ''
