_core:
  default_config_hash: W2w5PXSl9APjHQ6ePlJ0_e1qs-RcC-wTxqvI8iYbYCk
premier: 0
api_key: AIzaSyAGjrolV7VCpd5bnAj9zUyhEg5-zVZoCEw
secret: N0lcXiys2uCG4IV-oYQZf8ZXmic=
premium_client_id: ''
premium_crypto_key: ''
icon_url: ''
