_core:
  default_config_hash: W2w5PXSl9APjHQ6ePlJ0_e1qs-RcC-wTxqvI8iYbYCk
premier: 0
api_key: AIzaSyDHfO7--6HBrRMEXjIFT7k9esIgjYIZwJw
secret: 6BaKvIjchEO92E7fL-s4n1n2ArU=
premium_client_id: ''
premium_crypto_key: ''
icon_url: ''
