_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  action: 0
  address: 0
  address_static_map: 0
  addtocal_augment: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  animated_gif: 0
  automated_cron: 0
  ban: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  bulk_edit_terms: 0
  cache_control_override: 0
  cacheflush: 0
  cacheflush_entity: 0
  captcha: 0
  ckeditor5: 0
  ckeditor_link_styles: 0
  comment: 0
  components: 0
  config: 0
  config_direct_save: 0
  contact: 0
  contextual: 0
  csv_importer: 0
  date_augmenter: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  dropzonejs: 0
  dynamic_entity_reference: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  editor_advanced_link: 0
  ellison_webform: 0
  emulsify_twig: 0
  entity_browser: 0
  entity_embed: 0
  entity_reference_revisions: 0
  entity_usage: 0
  feeds: 0
  feeds_log: 0
  feeds_tamper: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  google_analytics: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  image_captcha: 0
  image_field_to_media: 0
  inline_form_errors: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  key: 0
  key_value_field: 0
  link: 0
  link_field_autocomplete_filter: 0
  linkit: 0
  mailsystem: 0
  media: 0
  media_bulk_upload: 0
  media_bulk_upload_dropzonejs: 0
  media_library: 0
  media_video_micromodal: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_import_export_csv: 0
  mimemail: 0
  mimemail_example: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_edit: 0
  paragraphs_library: 0
  pate: 0
  path: 0
  path_alias: 0
  phpass: 0
  quick_node_clone: 0
  recaptcha: 0
  recaptcha_v3: 0
  redirect: 0
  redirect_404: 0
  redirect_metrics: 0
  replicate: 0
  responsive_image: 0
  salesforce: 0
  salesforce_address: 0
  salesforce_jwt: 0
  salesforce_logger: 0
  salesforce_mapping: 0
  salesforce_mapping_ui: 0
  salesforce_oauth: 0
  salesforce_pull: 0
  salesforce_push: 0
  salesforce_soap: 0
  salesforce_webform: 0
  scheduler: 0
  search_api: 0
  search_api_db: 0
  search_api_db_defaults: 0
  search_api_page: 0
  sendgrid_integration: 0
  sendgrid_integration_reports: 0
  shortcut: 0
  simplify_menu: 0
  sitewide_alert: 0
  sitewide_alert_block: 0
  smart_date: 0
  smtp: 0
  system: 0
  tamper: 0
  taxonomy: 0
  taxonomy_manager: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_field_value: 0
  twig_tweak: 0
  typed_data: 0
  update: 0
  user: 0
  view_unpublished: 0
  views_bulk_edit: 0
  views_natural_sort: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_all_download: 0
  webform_attachment: 0
  webform_node: 0
  webform_pardot: 0
  webform_scheduled_email: 0
  webform_submissions_delete: 0
  webform_ui: 0
  pathauto: 1
  xmlsitemap: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  stable9: 0
  ellison: 0
profile: standard
