_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  address_static_map: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  components: 0
  config: 0
  contact: 0
  contextual: 0
  csv_importer: 0
  datetime: 0
  dblog: 0
  devel: 0
  dropzonejs: 0
  dynamic_entity_reference: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  ellison_webform: 0
  emulsify_twig: 0
  entity_reference_revisions: 0
  entity_usage: 0
  feeds: 0
  feeds_log: 0
  feeds_tamper: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  key: 0
  key_value_field: 0
  link: 0
  media: 0
  media_bulk_upload: 0
  media_bulk_upload_dropzonejs: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_edit: 0
  paragraphs_library: 0
  path: 0
  path_alias: 0
  quick_node_clone: 0
  responsive_image: 0
  salesforce: 0
  salesforce_address: 0
  salesforce_example: 0
  salesforce_jwt: 0
  salesforce_logger: 0
  salesforce_mapping: 0
  salesforce_mapping_ui: 0
  salesforce_oauth: 0
  salesforce_pull: 0
  salesforce_push: 0
  salesforce_soap: 0
  salesforce_webform: 0
  search: 0
  shortcut: 0
  smart_date: 0
  system: 0
  tamper: 0
  taxonomy: 0
  taxonomy_manager: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_field_value: 0
  twig_tweak: 0
  typed_data: 0
  update: 0
  user: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_node: 0
  webform_ui: 0
  pathauto: 1
  xmlsitemap: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  stable9: 0
  ellison: 0
profile: standard
