theme: current
defaults:
  sender: sendgrid_integration
  formatter: mime_mail
modules:
  smtp:
    none:
      sender: sendgrid_integration
      formatter: mime_mail
  webform:
    none:
      sender: sendgrid_integration
      formatter: mime_mail
  sendgrid_integration:
    none:
      sender: sendgrid_integration
      formatter: mime_mail
