_core:
  default_config_hash: rpfRQVoEn2ZWd_lw-iULKPiuina5CqcmzXWlz1OjTwM
name: 'Ellison Technologies'
mail: trinetdev3@trinetsolutions.com
simple_address: false
sitestyle: true
textonly: false
linkonly: false
user_plaintext_field: ''
format: basic_html
preserve_class: false
advanced:
  incoming: false
  key: lZB_6p7KIti-VGphOS84s6CrFNdZ3nXlJhWxZshaLlI
