_core:
  default_config_hash: rpfRQVoEn2ZWd_lw-iULKPiuina5CqcmzXWlz1OjTwM
name: 'Ellison Technologies'
mail: webcontact@ellisontechnologies.com
simple_address: true
sitestyle: true
textonly: false
linkonly: false
user_plaintext_field: ''
format: basic_html
preserve_class: false
advanced:
  incoming: false
  key: YzkDGKcbI9zazbbal2-Ka0sKS2VpjflFTYLi7BlKstI
