_core:
  default_config_hash: 6xvuojdlZ8-8Q7yJyRldPaE0UK_YijOlDo6HvURmW_E
site_key: 6Le_-jUqAAAAAOZWHXkUQHNe0ntxcrQNOM_iCsYK
secret_key: 6Le_-jUqAAAAAGVhm1gBN84PwR1-if77DfL8U_pv
hide_badge: false
verify_hostname: true
default_challenge: ''
error_message: 'Anti-bot verification failed.'
cacheable: false
library_use_recaptcha_net: false
