_core:
  default_config_hash: '-tOjnNKhQhxtuZFXdXARUeCOPANk0GCoqs6Ec7GwlV4'
langcode: en
id: salesforce_example_contact
label: 'Salesforce Example Contact'
weight: 0
type: salesforce_mapping
key: ''
always_upsert: null
async: false
push_standalone: false
pull_standalone: false
pull_trigger_date: LastModifiedDate
pull_frequency: 0
push_frequency: 0
push_limit: 0
push_retries: 3
pull_where_clause: ''
sync_triggers:
  push_create: true
  push_update: true
  push_delete: true
  pull_create: true
  pull_update: true
  pull_delete: true
salesforce_object_type: Contact
drupal_entity_type: user
drupal_bundle: user
field_mappings:
  -
    drupal_field_type: properties
    drupal_field_value: mail
    direction: sync
    salesforce_field: Email
    id: 0
  -
    drupal_field_type: properties
    drupal_field_value: name
    direction: sync
    salesforce_field: LastName
    id: 1
  -
    drupal_field_type: Constant
    drupal_field_value: Drupal
    direction: drupal_sf
    salesforce_field: LeadSource
    id: 2
status: true
dependencies:
  module:
    - salesforce_pull
    - salesforce_push
    - user
  enforced:
    module:
      - user
      - salesforce_example
uuid: a0f890d6-0704-46ae-a0f1-abf9ab739881
