_core:
  default_config_hash: HENvUIeX6xNPGRB1w3z6rT9a71LM_hKXATF6XrM9WvM
smtp_on: false
smtp_host: smtp.sendgrid.net
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_autotls: false
smtp_timeout: 60
smtp_username: apikey
smtp_password: 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
smtp_from: trinetdev3@trinetsolutions.com
smtp_fromname: 'Ellison Technologies'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: tim.bednar+359@trinetsolutions.com
smtp_reroute_address: ''
smtp_debugging: true
prev_mail_system: php_mail
smtp_keepalive: true
