_core:
  default_config_hash: HENvUIeX6xNPGRB1w3z6rT9a71LM_hKXATF6XrM9WvM
smtp_on: true
smtp_host: smtp.gmail.com
smtp_hostbackup: ''
smtp_port: '25'
smtp_protocol: ssl
smtp_autotls: false
smtp_timeout: 30
smtp_username: tim.bednar@trinetsolutions.com
smtp_password: Ywm9b2at
smtp_from: tim.bednar@trinetsolutions.com
smtp_fromname: 'Ellison Technologies'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: tim.bednar@gmail.com
smtp_reroute_address: tim.bednar@gmail.com
smtp_debugging: true
prev_mail_system: php_mail
smtp_keepalive: false
