_core:
  default_config_hash: HENvUIeX6xNPGRB1w3z6rT9a71LM_hKXATF6XrM9WvM
smtp_on: false
smtp_host: smtp.sendgrid.net
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: standard
smtp_autotls: false
smtp_timeout: 30
smtp_username: apikey
smtp_password: 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
smtp_from: trinetdev3@trinetsolutions.com
smtp_fromname: 'Ellison Technologies'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: tim.bednar@gmail.com
smtp_reroute_address: ''
smtp_debugging: false
prev_mail_system: php_mail
smtp_keepalive: false
