_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 22573375-0aaa-49e4-980a-cf3ac9c66092
name: 'Ellison Technologies'
mail: no-reply@ellisontechnologies.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
