<?php
/**
 * @file
 * Provides functionality for handling webform hook.
 */

/**
 * Implements hook_form_alter().
 */
function ellison_webform_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (strpos($form_id, 'webform_submission_contact') !== FALSE ||
    strpos($form_id, 'webform_submission_service_and_maintenance') !== FALSE ||
    strpos($form_id, 'webform_submission_parts_and_accessories') !== FALSE ||
    strpos($form_id, 'webform_submission_training_request') !== FALSE
  ) {
    $session = \Drupal::request()->getSession();
    $ellison_region = $session->get('ellison_region');

    $region = [];
    if (!empty($_COOKIE['ellison_region']) ) {
      $region = json_decode($_COOKIE['ellison_region'], TRUE);
    }
    elseif (!empty($ellison_region)) {
      $region = json_decode($ellison_region, TRUE);
    }
    if (!empty($region)) {
      if (isset($form['elements']['location']) || isset($form['elements']['select_location'])) {
        if (!empty($region['region_id'])) {
          $parent_id = $region['region_id'];
          $child_terms = \Drupal::entityTypeManager()
            ->getStorage('taxonomy_term')
            ->loadTree('regions', $parent_id, NULL, FALSE);
          $child_region = [];
          foreach ($child_terms as $term) {
            $child_region[$term->name] = $term->name;
          }
          if (isset($form['elements']['location'])) {
            $form['elements']['location']['#options'] = $child_region;
            if (empty($child_region)) {
              $form['elements']['location']['#access'] = FALSE;
            }
          }
          elseif (isset($form['elements']['select_location']) && !empty($child_region)) {
            $form['elements']['select_location']['#options'] = $child_region;
          }
        }
      }
      if (isset($form['elements']['region__c'])) {
        // Set the form element 'region__c' to the value of $region.
        if(is_array($region) && isset($region['sf_region_id']) && !empty($region['sf_region_id'])){
            $form['elements']['region__c']['#default_value'] = $region['sf_region_id'];
        }else{
            // default is salesforce southern california region id
            $form['elements']['region__c']['#default_value'] = '218';
        }
      }
      if (isset($form['elements']['webform_region_c'])) {
        // Set the form element 'region__c' to the value of $region.
        if(is_array($region) && isset($region['sf_region_id']) && !empty($region['sf_region_id'])){
            $form['elements']['webform_region_c']['#default_value'] = $region['sf_region_id'];
        }else{
            // default is salesforce southern california region id
            $form['elements']['webform_region_c']['#default_value'] = '218';
        }
      }
      if (isset($form['elements']['source_page_url'])) {
        $request_stack = \Drupal::service('request_stack');
        $request = $request_stack->getCurrentRequest();
        if ($request && $request->query->has('source_url')) {
          $form['elements']['source_page_url']['#default_value'] = $request->query->get('source_url');
        } else {
          $form['elements']['source_page_url']['#default_value'] = $request->getUri();
        }

      }
    }

  }


}
